apiVersion: v1
kind: Service
metadata:
  name: gunnidh-kaur-weather-project
  labels: 
    app: gunnidh_kaur_bits_id_2022ab12539
spec:
  type: LoadBalancer
  selector:
    app: gunnidh_kaur_bits_id_2022ab12539
  sessionAffinity: None
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000